### ISSUE TITLE
thermopile ignores `enable*` configurations

### ISSUE THREAD

**Issue by npry** [pchwalek/env_glasses#3]
## summary

Setting the `enable*` configuration options for the different thermopile sensor locations appears not to affect whether the sensors are individually enabled or not.

## repro

- Boot glasses
- Send config message to disable top of nose thermopile
- Observe continued data from the disabled thermopile

**Comment by pchwalek** [comment]
This issue stems from no selectivity code existing for the thermopile task. This has been resolved for the latest firmware.
